---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    etcd_for_all_users: true
  tasks:
    - name: Set download directory if install only for the user
      ansible.builtin.set_fact:
        etcd_runtime_dir: "{{ ansible_user_dir }}/bin"
      when: not etcd_for_all_users | bool

    - name: Set download directory for all users to use
      ansible.builtin.set_fact:
        etcd_runtime_dir: "/usr/local/bin"
      when: etcd_for_all_users | bool

    - name: Find the etcd file
      ansible.builtin.stat:
        path: "{{ etcd_runtime_dir }}/etcd"
      register: etcd_file

    - name: Print stat info
      ansible.builtin.debug:
        msg: "{{ etcd_file.stat }}"

    - name: Assert that etcd exists
      ansible.builtin.assert:
        that: etcd_file.stat.exists

    - name: Assert that etcd is executable
      ansible.builtin.assert:
        that: etcd_file.stat.executable
